name: datapack_migration
dependencies:
  build_runner:
  objd: ^0.3.5
  objd_gen: ^0.0.1
  logger: ^0.9.4
  numbers_to_words: ^0.1.2
environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  build_runner:
  objd_gen: ^0.0.1